version: '3.8'

services:

  front_react:
    image: front-react
    build: front
    container_name: front-react
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
    ports:
      - "5173:5173"