version: '3.8'

services:

  front_react:
    image: front_react
    build: front
    container_name: front_react
    volumes:
     - ./front/src:/app/src
     - ./front/public:/app/public
    ports:
      - "${FRONT_PORT}:5173"

  backend:
    depends_on:
      - dev_db
    image: backend
    build: back
    container_name: backend
    volumes:
      - ./back/prisma:/app/prisma
      - ./back/src:/app/src
      - ./back/.prettierrc:/app/.prettierrc
      - ./back/.nest-cli.json:/app/.nest-cli.json
    ports:
      - "${BACK_PORT}:3333"
    env_file:
      - .env

  dev_db:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    networks:
      - transcendance
    volumes:
      - dev_DB:/var/lib/postgresql/data


networks:
  transcendance:

volumes:
  dev_DB:
