version: '3.8'

services:

  front_react:
    image: front_react
    build: front
    container_name: front_react
    volumes:
     - ./front/src:/app/src
     - ./front/public:/app/public
    ports:
      - "${FRONT_PORT}:5173"
    networks:
      - transcendance

  dev_db:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - transcendance
    volumes:
      - dev_DB:/var/lib/postgresql/data

  backend:
    depends_on:
      - dev_db
    image: backend
    build: back
    container_name: backend
    volumes:
      - ./back/prisma:/app/prisma
      - ./back/src:/app/src
      - ./back/.prettierrc:/app/.prettierrc
      - ./back/.nest-cli.json:/app/.nest-cli.json
    ports:
      - "${BACK_PORT}:${BACK_PORT}"
    networks:
      - transcendance
    env_file:
      - .env
    environment:   # Ajoutez cette ligne pour partager DATABASE_URL avec le service backend
      DATABASE_URL: ${DATABASE_URL}
    #command: >
    #  sh -c "npx prisma migrate dev --name newMigration deploy && npm run start:dev"
    # command: >
    #   sh -c "until pg_isready -h dev_db -p ${DB_PORT}; do echo 'Waiting for database to become available...' && sleep 1; done &&
    #   npx prisma migrate dev --name newMigration deploy && npm run start:dev"
    command: >
      sh -c "until pg_isready -h dev_db -p ${DB_PORT}; do echo 'Waiting for database to become available...' && sleep 1; done &&
      npx prisma migrate dev --name newMigration deploy && npx prisma generate && npm run start:dev"

networks:
  transcendance:

volumes:
  dev_DB:
